/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thehumangeo.twitter.centrality.domain;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class StatusUserEntitiesDescription implements org.apache.thrift.TBase<StatusUserEntitiesDescription, StatusUserEntitiesDescription._Fields>, java.io.Serializable, Cloneable, Comparable<StatusUserEntitiesDescription> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("StatusUserEntitiesDescription");

  private static final org.apache.thrift.protocol.TField URLS_FIELD_DESC = new org.apache.thrift.protocol.TField("urls", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new StatusUserEntitiesDescriptionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new StatusUserEntitiesDescriptionTupleSchemeFactory());
  }

  public List<String> urls; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    URLS((short)1, "urls");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // URLS
          return URLS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.URLS, new org.apache.thrift.meta_data.FieldMetaData("urls", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(StatusUserEntitiesDescription.class, metaDataMap);
  }

  public StatusUserEntitiesDescription() {
  }

  public StatusUserEntitiesDescription(
    List<String> urls)
  {
    this();
    this.urls = urls;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public StatusUserEntitiesDescription(StatusUserEntitiesDescription other) {
    if (other.isSetUrls()) {
      List<String> __this__urls = new ArrayList<String>(other.urls);
      this.urls = __this__urls;
    }
  }

  public StatusUserEntitiesDescription deepCopy() {
    return new StatusUserEntitiesDescription(this);
  }

  @Override
  public void clear() {
    this.urls = null;
  }

  public int getUrlsSize() {
    return (this.urls == null) ? 0 : this.urls.size();
  }

  public java.util.Iterator<String> getUrlsIterator() {
    return (this.urls == null) ? null : this.urls.iterator();
  }

  public void addToUrls(String elem) {
    if (this.urls == null) {
      this.urls = new ArrayList<String>();
    }
    this.urls.add(elem);
  }

  public List<String> getUrls() {
    return this.urls;
  }

  public StatusUserEntitiesDescription setUrls(List<String> urls) {
    this.urls = urls;
    return this;
  }

  public void unsetUrls() {
    this.urls = null;
  }

  /** Returns true if field urls is set (has been assigned a value) and false otherwise */
  public boolean isSetUrls() {
    return this.urls != null;
  }

  public void setUrlsIsSet(boolean value) {
    if (!value) {
      this.urls = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case URLS:
      if (value == null) {
        unsetUrls();
      } else {
        setUrls((List<String>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case URLS:
      return getUrls();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case URLS:
      return isSetUrls();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof StatusUserEntitiesDescription)
      return this.equals((StatusUserEntitiesDescription)that);
    return false;
  }

  public boolean equals(StatusUserEntitiesDescription that) {
    if (that == null)
      return false;

    boolean this_present_urls = true && this.isSetUrls();
    boolean that_present_urls = true && that.isSetUrls();
    if (this_present_urls || that_present_urls) {
      if (!(this_present_urls && that_present_urls))
        return false;
      if (!this.urls.equals(that.urls))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(StatusUserEntitiesDescription other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetUrls()).compareTo(other.isSetUrls());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUrls()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.urls, other.urls);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("StatusUserEntitiesDescription(");
    boolean first = true;

    sb.append("urls:");
    if (this.urls == null) {
      sb.append("null");
    } else {
      sb.append(this.urls);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (urls == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'urls' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class StatusUserEntitiesDescriptionStandardSchemeFactory implements SchemeFactory {
    public StatusUserEntitiesDescriptionStandardScheme getScheme() {
      return new StatusUserEntitiesDescriptionStandardScheme();
    }
  }

  private static class StatusUserEntitiesDescriptionStandardScheme extends StandardScheme<StatusUserEntitiesDescription> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, StatusUserEntitiesDescription struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // URLS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.urls = new ArrayList<String>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  String _elem2;
                  _elem2 = iprot.readString();
                  struct.urls.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setUrlsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, StatusUserEntitiesDescription struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.urls != null) {
        oprot.writeFieldBegin(URLS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.urls.size()));
          for (String _iter3 : struct.urls)
          {
            oprot.writeString(_iter3);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class StatusUserEntitiesDescriptionTupleSchemeFactory implements SchemeFactory {
    public StatusUserEntitiesDescriptionTupleScheme getScheme() {
      return new StatusUserEntitiesDescriptionTupleScheme();
    }
  }

  private static class StatusUserEntitiesDescriptionTupleScheme extends TupleScheme<StatusUserEntitiesDescription> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, StatusUserEntitiesDescription struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.urls.size());
        for (String _iter4 : struct.urls)
        {
          oprot.writeString(_iter4);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, StatusUserEntitiesDescription struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, iprot.readI32());
        struct.urls = new ArrayList<String>(_list5.size);
        for (int _i6 = 0; _i6 < _list5.size; ++_i6)
        {
          String _elem7;
          _elem7 = iprot.readString();
          struct.urls.add(_elem7);
        }
      }
      struct.setUrlsIsSet(true);
    }
  }

}

