/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.thehumangeo.twitter.centrality.domain;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class StatusMetadata implements org.apache.thrift.TBase<StatusMetadata, StatusMetadata._Fields>, java.io.Serializable, Cloneable, Comparable<StatusMetadata> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("StatusMetadata");

  private static final org.apache.thrift.protocol.TField ISO_LANGUAGE_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("isoLanguageCode", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField RESULT_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("resultType", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new StatusMetadataStandardSchemeFactory());
    schemes.put(TupleScheme.class, new StatusMetadataTupleSchemeFactory());
  }

  public String isoLanguageCode; // required
  public String resultType; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ISO_LANGUAGE_CODE((short)1, "isoLanguageCode"),
    RESULT_TYPE((short)2, "resultType");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ISO_LANGUAGE_CODE
          return ISO_LANGUAGE_CODE;
        case 2: // RESULT_TYPE
          return RESULT_TYPE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ISO_LANGUAGE_CODE, new org.apache.thrift.meta_data.FieldMetaData("isoLanguageCode", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RESULT_TYPE, new org.apache.thrift.meta_data.FieldMetaData("resultType", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(StatusMetadata.class, metaDataMap);
  }

  public StatusMetadata() {
  }

  public StatusMetadata(
    String isoLanguageCode,
    String resultType)
  {
    this();
    this.isoLanguageCode = isoLanguageCode;
    this.resultType = resultType;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public StatusMetadata(StatusMetadata other) {
    if (other.isSetIsoLanguageCode()) {
      this.isoLanguageCode = other.isoLanguageCode;
    }
    if (other.isSetResultType()) {
      this.resultType = other.resultType;
    }
  }

  public StatusMetadata deepCopy() {
    return new StatusMetadata(this);
  }

  @Override
  public void clear() {
    this.isoLanguageCode = null;
    this.resultType = null;
  }

  public String getIsoLanguageCode() {
    return this.isoLanguageCode;
  }

  public StatusMetadata setIsoLanguageCode(String isoLanguageCode) {
    this.isoLanguageCode = isoLanguageCode;
    return this;
  }

  public void unsetIsoLanguageCode() {
    this.isoLanguageCode = null;
  }

  /** Returns true if field isoLanguageCode is set (has been assigned a value) and false otherwise */
  public boolean isSetIsoLanguageCode() {
    return this.isoLanguageCode != null;
  }

  public void setIsoLanguageCodeIsSet(boolean value) {
    if (!value) {
      this.isoLanguageCode = null;
    }
  }

  public String getResultType() {
    return this.resultType;
  }

  public StatusMetadata setResultType(String resultType) {
    this.resultType = resultType;
    return this;
  }

  public void unsetResultType() {
    this.resultType = null;
  }

  /** Returns true if field resultType is set (has been assigned a value) and false otherwise */
  public boolean isSetResultType() {
    return this.resultType != null;
  }

  public void setResultTypeIsSet(boolean value) {
    if (!value) {
      this.resultType = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ISO_LANGUAGE_CODE:
      if (value == null) {
        unsetIsoLanguageCode();
      } else {
        setIsoLanguageCode((String)value);
      }
      break;

    case RESULT_TYPE:
      if (value == null) {
        unsetResultType();
      } else {
        setResultType((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ISO_LANGUAGE_CODE:
      return getIsoLanguageCode();

    case RESULT_TYPE:
      return getResultType();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ISO_LANGUAGE_CODE:
      return isSetIsoLanguageCode();
    case RESULT_TYPE:
      return isSetResultType();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof StatusMetadata)
      return this.equals((StatusMetadata)that);
    return false;
  }

  public boolean equals(StatusMetadata that) {
    if (that == null)
      return false;

    boolean this_present_isoLanguageCode = true && this.isSetIsoLanguageCode();
    boolean that_present_isoLanguageCode = true && that.isSetIsoLanguageCode();
    if (this_present_isoLanguageCode || that_present_isoLanguageCode) {
      if (!(this_present_isoLanguageCode && that_present_isoLanguageCode))
        return false;
      if (!this.isoLanguageCode.equals(that.isoLanguageCode))
        return false;
    }

    boolean this_present_resultType = true && this.isSetResultType();
    boolean that_present_resultType = true && that.isSetResultType();
    if (this_present_resultType || that_present_resultType) {
      if (!(this_present_resultType && that_present_resultType))
        return false;
      if (!this.resultType.equals(that.resultType))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(StatusMetadata other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetIsoLanguageCode()).compareTo(other.isSetIsoLanguageCode());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIsoLanguageCode()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.isoLanguageCode, other.isoLanguageCode);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResultType()).compareTo(other.isSetResultType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResultType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.resultType, other.resultType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("StatusMetadata(");
    boolean first = true;

    sb.append("isoLanguageCode:");
    if (this.isoLanguageCode == null) {
      sb.append("null");
    } else {
      sb.append(this.isoLanguageCode);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("resultType:");
    if (this.resultType == null) {
      sb.append("null");
    } else {
      sb.append(this.resultType);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (isoLanguageCode == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'isoLanguageCode' was not present! Struct: " + toString());
    }
    if (resultType == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'resultType' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class StatusMetadataStandardSchemeFactory implements SchemeFactory {
    public StatusMetadataStandardScheme getScheme() {
      return new StatusMetadataStandardScheme();
    }
  }

  private static class StatusMetadataStandardScheme extends StandardScheme<StatusMetadata> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, StatusMetadata struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ISO_LANGUAGE_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.isoLanguageCode = iprot.readString();
              struct.setIsoLanguageCodeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESULT_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.resultType = iprot.readString();
              struct.setResultTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, StatusMetadata struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.isoLanguageCode != null) {
        oprot.writeFieldBegin(ISO_LANGUAGE_CODE_FIELD_DESC);
        oprot.writeString(struct.isoLanguageCode);
        oprot.writeFieldEnd();
      }
      if (struct.resultType != null) {
        oprot.writeFieldBegin(RESULT_TYPE_FIELD_DESC);
        oprot.writeString(struct.resultType);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class StatusMetadataTupleSchemeFactory implements SchemeFactory {
    public StatusMetadataTupleScheme getScheme() {
      return new StatusMetadataTupleScheme();
    }
  }

  private static class StatusMetadataTupleScheme extends TupleScheme<StatusMetadata> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, StatusMetadata struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.isoLanguageCode);
      oprot.writeString(struct.resultType);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, StatusMetadata struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.isoLanguageCode = iprot.readString();
      struct.setIsoLanguageCodeIsSet(true);
      struct.resultType = iprot.readString();
      struct.setResultTypeIsSet(true);
    }
  }

}

